// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfmSAu6C88UAsPHWO3MORqRoHIeNRBQS4',
    appId: '1:57207584933:web:2e772d7b9c88ab01c1b54c',
    messagingSenderId: '57207584933',
    projectId: 'flutterfirebase-b66a6',
    authDomain: 'flutterfirebase-b66a6.firebaseapp.com',
    storageBucket: 'flutterfirebase-b66a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbf7YLbNtVTo26iOpM8g4Kh8FUBElUYs',
    appId: '1:57207584933:android:718dc3902c5dd3bbc1b54c',
    messagingSenderId: '57207584933',
    projectId: 'flutterfirebase-b66a6',
    storageBucket: 'flutterfirebase-b66a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIWxhiEREthIWH22GITSWA4pfNs43KaY',
    appId: '1:57207584933:ios:4cd6f0d22881292cc1b54c',
    messagingSenderId: '57207584933',
    projectId: 'flutterfirebase-b66a6',
    storageBucket: 'flutterfirebase-b66a6.appspot.com',
    iosClientId: '57207584933-5bhp5sqnvu0c5v9vktn6028hqil9dh0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIWxhiEREthIWH22GITSWA4pfNs43KaY',
    appId: '1:57207584933:ios:4cd6f0d22881292cc1b54c',
    messagingSenderId: '57207584933',
    projectId: 'flutterfirebase-b66a6',
    storageBucket: 'flutterfirebase-b66a6.appspot.com',
    iosClientId: '57207584933-5bhp5sqnvu0c5v9vktn6028hqil9dh0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
